# -*- coding: utf-8 -*-
"""insurance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14xauycYWCiQ981C751IsrXq5-k890aqQ
"""

# -*- coding: utf-8 -*-

from pathlib import Path
import os
import pandas as pd

try:
    import google.colab  # noqa
    IS_COLAB = True
except Exception:
    IS_COLAB = False

ROOT = Path(__file__).parent
candidates = [
    os.environ.get("INS_CSV_PATH"),
    ROOT / "csv" / "insurance_core.csv",
    ROOT / "insurance_core.csv"
]

CSV_PATH = None
for c in candidates:
    if not c:
        continue
    p = Path(c).expanduser().resolve()
    if p.exists():
        CSV_PATH = str(p)
        break

if IS_COLAB:
    from google.colab import files  # type: ignore
    uploaded = files.upload()
    CSV_PATH = "insurance_core.csv"

if not CSV_PATH:
    raise FileNotFoundError("insurance_core.csv not found in expected locations.")

# === CSV 불러오기 ===
insurance_df = pd.read_csv(CSV_PATH)

insurance_df.columns

# 전처리 해야하지만
# 랜덤포레스트 모델 사용할거면 안 해도 됨..
# KNN 분류 모델 할거면 전처리
insurance_df.describe()

from sklearn.preprocessing import LabelEncoder

# 학습 전 문자열을 숫자로 바꾸는 과정
job = LabelEncoder()
jobrisk = LabelEncoder()
product = LabelEncoder()
gender = LabelEncoder()

insurance_df["직업"] = job.fit_transform(insurance_df["직업"])
insurance_df["직업 위험도"] = jobrisk.fit_transform(insurance_df["직업 위험도"])
insurance_df["상품명"] = product.fit_transform(insurance_df["상품명"])
insurance_df["성별"] = gender.fit_transform(insurance_df["성별"])

data = insurance_df[['남자(보험료)','지급금액','직업','나이','여자(보험료)','성별','직업 위험도','가입금액']].to_numpy()

target = insurance_df['상품명'].to_numpy()

data

target

# 훈련세트 와 테스트 세트 나누기
# 8:2로 나누기
from sklearn.model_selection import train_test_split

#test_size=0.2 20% 한다.
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)


# 전처리 : 표준화하기
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input) # 훈련데이터에서 훈련한다..

train_scaled = ss.transform(train_input) # 훈련 세트 변환
test_scaled = ss.transform(test_input) # 테스트 세트 변환

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

# 여자 데이터셋
df_f = insurance_df[insurance_df["성별"]==0].copy()
X_f = df_f[["여자(보험료)", "지급금액", "나이", "직업", "직업 위험도"]].astype(float).values
scaler_f = StandardScaler().fit(X_f)
X_f_scaled = scaler_f.transform(X_f)
knn_f = NearestNeighbors(n_neighbors=5, metric="euclidean").fit(X_f_scaled)

# 남자 데이터셋
df_m = insurance_df[insurance_df["성별"]==1].copy()
X_m = df_m[["남자(보험료)", "지급금액", "나이", "직업", "직업 위험도"]].astype(float).values
scaler_m = StandardScaler().fit(X_m)
X_m_scaled = scaler_m.transform(X_m)
knn_m = NearestNeighbors(n_neighbors=5, metric="euclidean").fit(X_m_scaled)

from sklearn.neighbors import NearestNeighbors
from difflib import get_close_matches
import numpy as np
import pandas as pd

def build_job_to_risk_lookup(df, job_col="직업(원문)", risk_col="직업 위험도(원문)"):
    if job_col in df.columns and risk_col in df.columns:
        return df.groupby(job_col)[risk_col].agg(lambda s: s.mode().iloc[0]).to_dict()
    return None

job2risk_lookup = build_job_to_risk_lookup(insurance_df)

def _coerce_gender(g):
    if isinstance(g, str):
        g = g.strip()
        if g in ("남", "남자", "M", "male", "Male"):
            return 1
        if g in ("여", "여자", "F", "female", "Female"):
            return 0
        raise ValueError(f"성별 해석 불가: {g}")
    return int(g)

def _to_job_code(job_text):
    labels = list(job.classes_)
    if job_text in labels:
        return int(job.transform([job_text])[0])
    cand = get_close_matches(job_text, labels, n=1, cutoff=0.6)
    if not cand:
        raise ValueError(f"알 수 없는 직업: {job_text}")
    return int(job.transform([cand[0]])[0])

def _infer_risk_from_job(job_text):
    if job2risk_lookup and job_text in job2risk_lookup:
        risk_text = job2risk_lookup[job_text]
        return int(jobrisk.transform([risk_text])[0])
    try:
        j_code = _to_job_code(job_text)
    except:
        return None
    sub = insurance_df[insurance_df["직업"] == j_code]
    if sub.empty:
        return None
    mode_val = sub["직업 위험도"].mode()
    return int(mode_val.iloc[0]) if not mode_val.empty else None

def _restore_product_names(series_like):

    try:
        if series_like.dtype == object:
            return series_like
        return pd.Series(product.inverse_transform(series_like.astype(int)), index=series_like.index)
    except Exception:
        return series_like

def recommend_top_k(gender_input, premium, coverage, age, job_text, k=5, sort_by="distance"):

    g = _coerce_gender(gender_input)
    j_code = _to_job_code(job_text)
    r_code = _infer_risk_from_job(job_text)
    if r_code is None:
        r_code = int(insurance_df["직업 위험도"].mode().iloc[0])

    base_vec = np.array([[float(premium), float(coverage), float(age), float(j_code), float(r_code)]], dtype=float)

    if g == 0:
        premium_col = "여자(보험료)"
        pool_df = df_f
        q_scaled = scaler_f.transform(base_vec)
        X_pool_scaled = X_f_scaled
    else:
        premium_col = "남자(보험료)"
        pool_df = df_m
        q_scaled = scaler_m.transform(base_vec)
        X_pool_scaled = X_m_scaled

    mask = pool_df[premium_col] <= float(premium)
    idxs = np.where(mask.values)[0]

    if len(idxs) == 0:
        cols = ["상품명", premium_col, "지급금액", "나이"]
        if "직업(원문)" in pool_df.columns:
            cols += ["직업(원문)", "직업 위험도(원문)"]
        return pd.DataFrame(columns=cols)

    diffs = X_pool_scaled[idxs] - q_scaled
    dists = np.linalg.norm(diffs, axis=1)

    rec_rows = pool_df.iloc[idxs].copy()
    rec_rows["상품명"] = _restore_product_names(rec_rows["상품명"])
    rec_rows["_distance"] = dists

    if sort_by == "premium":
        rec_rows["_sortkey"] = (rec_rows[premium_col] - premium).abs()
    elif sort_by == "coverage":
        rec_rows["_sortkey"] = (rec_rows["지급금액"] - coverage).abs()
    else:  # distance
        rec_rows["_sortkey"] = rec_rows["_distance"]

    rec_rows = rec_rows.sort_values(by="_sortkey", ascending=True).head(k)

    show_cols = ["상품명", premium_col, "지급금액", "나이"]
    if "직업(원문)" in pool_df.columns:
        show_cols += ["직업(원문)", "직업 위험도(원문)"]

    return rec_rows[show_cols].reset_index(drop=True)

res = recommend_top_k(
    gender_input="남자",
    premium=50000,
    coverage=20000000,
    age=25,
    job_text="사무직",
    k=10,
    sort_by="coverage"    # 정렬 기준: "distance" | "premium" | "coverage"
)

print(res.to_string(index=False))